### ISSUE TITLE
Add some tests for various mp4 containers

### ISSUE THREAD

**Issue by emilk** [rerun-io/re_mp4#3]
https://github.com/rerun-io/re_mp4/blob/master/tests/lib.rs has code in it, but it is never run

We need to store the test videos somewhere, e.g. on Google Drive or git LFS

**Comment by Wumpf** [comment]
a bunch of snapshot tests with various variants would be fine
Vary on:
* codecs
* add audio & subtile streams
* many streams 
* stuff
